#pragma once

#include "DistanceMonitorConfig.h"

#include <cstddef>
#include <cstdint>

/** Current radio freshness state of a configured Distance Monitor member. */
enum class DmRadioState : uint8_t
{
    /** No trustworthy radio age can currently be established. */
    Unknown = 0,

    /** The member has been heard within DM_LAST_HEARD_STALE_S. */
    Alive,

    /** The member should still exist but has not been heard recently enough. */
    Stale,

    /** The member has not been heard for at least DM_LAST_HEARD_LOST_S. */
    Lost,
};

/** Detailed usability state of the latest GNSS sample known for a member. */
enum class DmPositionState : uint8_t
{
    /** Coordinates may exist, but quality and/or freshness are not trustworthy yet. */
    Unknown = 0,

    /** No coordinates are currently available. */
    Missing,

    /** The reported GNSS fix type is below DM_MIN_FIX_TYPE. */
    NoFix,

    /** HDOP is zero or above the configured maximum. */
    PoorHdop,

    /** No GNSS/sample timestamp or runtime receive age can be established. */
    NoTimestamp,

    /** A reported absolute timestamp is in the future and therefore inconsistent. */
    InvalidTimestamp,

    /** The sample is valid but is at least DM_POSITION_MAX_AGE_S old. */
    Stale,

    /** Coordinates, fix quality, HDOP and freshness are acceptable. */
    Valid,
};

/** Source used to calculate the displayed GNSS/sample age. */
enum class DmPositionAgeSource : uint8_t
{
    /** No reliable age source is currently available. */
    None = 0,

    /** Age came from Position.timestamp, the actual GNSS solution timestamp. */
    GnssTimestamp,

    /** Age came from Position.time when the GNSS solution timestamp was absent. */
    PositionTime,

    /** Age came from monotonic time since this POSITION_APP packet was received. */
    PacketReception,
};

/** Confidence state of the distance value exposed for one remote member. */
enum class DmDistanceState : uint8_t
{
    /** No sufficiently reliable distance can currently be provided. */
    Unknown = 0,

    /** This state represents the local node itself. */
    Local,

    /** Distance was calculated from two currently usable GNSS positions. */
    Valid,

    /**
     * The last valid distance is temporarily retained during a short GNSS
     * dropout. This retained value is not a new distance measurement.
     */
    Grace,
};

/** Distance-zone/alarm state maintained by a base for one remote member. */
enum class DmAlarmState : uint8_t
{
    /** Current valid distance is below 80 percent of the configured maximum. */
    Safe = 0,

    /** Current valid distance is between 80 and 100 percent of the maximum. */
    Warning,

    /** Current valid distance is above 100 percent of the maximum. */
    Alarm,

    /** Tracking information has been unavailable for longer than the grace period. */
    TrackingLost,
};

/** Message types carried by the Distance Monitor PRIVATE_APP protocol. */
enum class DmMessageType : uint8_t
{
    /** Ask a configured member to prove that its Distance Monitor module is alive. */
    AliveRequest = 1,

    /** Application-level response to an AliveRequest. */
    AliveResponse = 2,

    /** Emergency event generated by a user double press. */
    Sos = 3,
};

/** Mutable configuration of one Distance Monitor member. */
struct DmMemberConfig
{
    /** Meshtastic node number identifying this member. */
    uint32_t nodeNum = 0U;

    /** True when this member acts as a monitoring base. */
    bool isBase = false;
};

/**
 * Mutable configuration used by the running module.
 *
 * It is initialized from compile-time defaults today. It is intentionally not
 * constexpr so a future application/persistence layer can replace member IDs,
 * base flags and thresholds without changing the monitoring code.
 */
struct DmRuntimeConfig
{
    /** Number of valid entries in members[]. */
    size_t memberCount = 0U;

    /** Configured Distance Monitor group members. */
    DmMemberConfig members[DM_MAX_MEMBERS] = {};

    /** Maximum monitoring distance in meters. */
    float maxDistanceMeters = DM_MAX_DISTANCE_M;

    /** Ratio at which the warning zone starts. */
    float warningRatio = DM_WARNING_RATIO;

    /** Maximum accepted HDOP in Meshtastic 1/100 units. */
    uint32_t maxHdop = DM_MAX_HDOP;

    /** Maximum accepted GNSS/sample age in seconds. */
    uint32_t positionMaxAgeSeconds = DM_POSITION_MAX_AGE_S;
};

/** Dynamic runtime state maintained for one configured member. */
struct DmNodeState
{
    // ---------------------------------------------------------------------
    // Identity and membership
    // ---------------------------------------------------------------------

    /** Meshtastic node number copied from the member configuration. */
    uint32_t nodeNum = 0U;

    /** True when this state belongs to the device running this firmware. */
    bool isLocal = false;

    /** True when this configured member is a monitoring base. */
    bool isBase = false;

    /** True when a NodeInfoLite entry for this member currently exists in NodeDB. */
    bool presentInNodeDB = false;

    // ---------------------------------------------------------------------
    // Radio liveness
    // ---------------------------------------------------------------------

    /** Last absolute Meshtastic last_heard timestamp observed for this member. */
    uint32_t lastHeard = 0U;

    /** Calculated age of lastHeard in seconds. */
    uint32_t lastHeardAgeSeconds = 0U;

    /** True when lastHeardAgeSeconds contains a meaningful value. */
    bool hasLastHeardAge = false;

    /** Current radio freshness classification. */
    DmRadioState radioState = DmRadioState::Unknown;

    /** Monotonic receive time of the latest packet observed from this member. */
    uint32_t lastPacketRxMs = 0U;

    /** True once lastPacketRxMs contains a real packet reception time. */
    bool hasPacketRxTime = false;

    /** Monotonic time when the latest ALIVE_REQUEST was sent to this member. */
    uint32_t lastAliveRequestMs = 0U;

    /** True after at least one ALIVE_REQUEST has been sent to this member. */
    bool hasAliveRequestTime = false;

    // ---------------------------------------------------------------------
    // GNSS sample and quality
    // ---------------------------------------------------------------------

    /** True after a full meshtastic_Position payload has been captured. */
    bool hasFullPositionSample = false;

    /** True when the latest captured sample contains latitude and longitude. */
    bool hasCoordinates = false;

    /** Latitude in Meshtastic integer degrees (degrees multiplied by 1e7). */
    int32_t latitudeI = 0;

    /** Longitude in Meshtastic integer degrees (degrees multiplied by 1e7). */
    int32_t longitudeI = 0;

    /** Actual GNSS solution timestamp from Position.timestamp, when supplied. */
    uint32_t positionTimestamp = 0U;

    /** Position.time fallback supplied by Meshtastic, when available. */
    uint32_t positionTime = 0U;

    /** HDOP in Meshtastic 1/100 units; 300 means 3.00. */
    uint32_t hdop = 0U;

    /** GNSS fix type reported by Meshtastic. */
    uint32_t fixType = 0U;

    /** GNSS fix quality reported by Meshtastic. */
    uint32_t fixQuality = 0U;

    /** Number of satellites in view reported by Meshtastic. */
    uint32_t satellitesInView = 0U;

    /** Calculated age of the latest GNSS/sample information in seconds. */
    uint32_t positionAgeSeconds = 0U;

    /** True when positionAgeSeconds contains a meaningful value. */
    bool hasPositionAge = false;

    /** Source used to calculate positionAgeSeconds. */
    DmPositionAgeSource positionAgeSource = DmPositionAgeSource::None;

    /** Current detailed GNSS usability classification. */
    DmPositionState positionState = DmPositionState::Unknown;

    /** Monotonic receive time of the latest decoded POSITION_APP packet. */
    uint32_t lastPositionRxMs = 0U;

    /** True once a decoded POSITION_APP packet has been observed since boot. */
    bool hasPositionRxTime = false;

    /** Monotonic time when the latest POSITION_APP request was sent to this member. */
    uint32_t lastPositionRequestMs = 0U;

    /** True after at least one position request has been sent to this member. */
    bool hasPositionRequestTime = false;

    // ---------------------------------------------------------------------
    // Distance and alarm state
    // ---------------------------------------------------------------------

    /** Current confidence state of distanceMeters. */
    DmDistanceState distanceState = DmDistanceState::Unknown;

    /** Current distance in meters; may contain a retained value during Grace. */
    double distanceMeters = 0.0;

    /** True once at least one fully valid distance has been calculated. */
    bool hasLastValidDistance = false;

    /** Most recent distance calculated from two currently usable positions. */
    double lastValidDistanceMeters = 0.0;

    /** Monotonic time when lastValidDistanceMeters was calculated. */
    uint32_t lastValidDistanceMs = 0U;

    /** Current base-side alarm zone for this member. */
    DmAlarmState alarmState = DmAlarmState::Safe;

    /** True while the current local warning/alarm is temporarily acknowledged. */
    bool alarmAcknowledged = false;

    /** Monotonic time of the latest local alarm acknowledgement. */
    uint32_t alarmAcknowledgedMs = 0U;

    // ---------------------------------------------------------------------
    // Direct-link radio metrics
    // ---------------------------------------------------------------------

    /** True when at least one direct-link RSSI/SNR sample is available. */
    bool radioMetricsValid = false;

    /** Latest direct-link RSSI sample in dBm. */
    int16_t rssi = 0;

    /** Latest direct-link SNR sample in dB. */
    float snr = 0.0F;

    /** Exponentially filtered direct-link RSSI in dBm. */
    float filteredRssi = 0.0F;

    /** Change in filtered RSSI between the two latest direct samples. */
    float rssiTrend = 0.0F;

    /** True once the exponential RSSI filter has received its first sample. */
    bool rssiFilterInitialized = false;

    // ---------------------------------------------------------------------
    // Private application protocol state
    // ---------------------------------------------------------------------

    /** Latest accepted sender-local Distance Monitor sequence number. */
    uint32_t lastSeqNum = 0U;

    /** True once lastSeqNum contains an accepted application sequence. */
    bool hasLastSeqNum = false;

    /** Monotonic receive time associated with lastSeqNum. */
    uint32_t lastSeqRxMs = 0U;

    /** True when a received SOS is pending future buzzer/UI handling. */
    bool sosPending = false;
};

/** Decoded fixed header of one Distance Monitor PRIVATE_APP message. */
struct DmMessageHeader
{
    /** Distance Monitor protocol version used by the sender. */
    uint8_t version = 0U;

    /** Semantic type of the private application message. */
    DmMessageType type = DmMessageType::AliveRequest;

    /** Sender-local monotonically increasing application sequence number. */
    uint32_t sequence = 0U;
};
